// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmSO3ChqCKJ7LQndRRV-e6glT4WcoVUGQ',
    appId: '1:631211969993:web:7c3fea0097939d1b13ac18',
    messagingSenderId: '631211969993',
    projectId: 'scan-life-2024',
    authDomain: 'scan-life-2024.firebaseapp.com',
    storageBucket: 'scan-life-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnTLTaCTkFfzMwtrQ_jm_303RF39lXP08',
    appId: '1:631211969993:android:d644726c777825c413ac18',
    messagingSenderId: '631211969993',
    projectId: 'scan-life-2024',
    storageBucket: 'scan-life-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGxmqCsk05RWCIsxbHTu0_O06BWlhSMJY',
    appId: '1:631211969993:ios:4efd27880cf4fed413ac18',
    messagingSenderId: '631211969993',
    projectId: 'scan-life-2024',
    storageBucket: 'scan-life-2024.appspot.com',
    iosBundleId: 'com.example.scanLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGxmqCsk05RWCIsxbHTu0_O06BWlhSMJY',
    appId: '1:631211969993:ios:4efd27880cf4fed413ac18',
    messagingSenderId: '631211969993',
    projectId: 'scan-life-2024',
    storageBucket: 'scan-life-2024.appspot.com',
    iosBundleId: 'com.example.scanLife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmSO3ChqCKJ7LQndRRV-e6glT4WcoVUGQ',
    appId: '1:631211969993:web:165ad8ceb033f60b13ac18',
    messagingSenderId: '631211969993',
    projectId: 'scan-life-2024',
    authDomain: 'scan-life-2024.firebaseapp.com',
    storageBucket: 'scan-life-2024.appspot.com',
  );
}
